name: Runner

on:
  schedule:
    # Script dijalankan tiap jam 11:00 UTC (18:00 WIB)
    # Weekday (1-5) only
    - cron: "00 11 * * 1-5"

  push:
    branches: [master, selenium]

jobs:
  Runner:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone wildangunawan/Dataset-Saham-IDX into data folder
        run: git clone https://github.com/wildangunawan/Dataset-Saham-IDX.git data

      - name: "Setup chromedriver"
        uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run get-list-emiten.py
        run: python get-list-emiten.py

      - name: Check working directory
        run: dir .

      - name: Check working retrieved data
        run: dir "./data/List Emiten"
